import subprocess,time,urllib.request,json,tempfile,zipfile,io,os,sys
from pathlib import Path
from playwright.sync_api import sync_playwright
wheel=os.environ.get('CUSTOMCHAT_TEST_PYTHON',sys.executable);url='http://127.0.0.1:8098';tmp=tempfile.TemporaryDirectory();root=Path(tmp.name);(root/'app.yaml').write_text('app: {title: Current Nerd}\nprovider: {type: mock}\nsources: []\n');(root/'docs').mkdir();(root/'docs'/'keep.md').write_text('current app must stay')
proc=subprocess.Popen([wheel,'-m','customchat','run',str(root/'app.yaml'),'--port','8098','--no-browser'],cwd='/tmp',stdout=open('/tmp/017-drop-server.log','w'),stderr=subprocess.STDOUT)
def make_zip(files):
 data=io.BytesIO()
 with zipfile.ZipFile(data,'w') as z:
  for k,v in files.items():z.writestr(k,v)
 return list(data.getvalue())
bundle=make_zip({'app.yaml':'app: {title: Dropped Nerd}\nprovider: {type: mock}\nsources: [{id: docs, type: local_files, path: docs}]\n','docs/guide.md':'# Drop zip guide\nCustomChat imports Nerd ZIP bundles into a separate local workspace. Drop a ZIP to review it first.'})
try:
 for _ in range(80):
  try:urllib.request.urlopen(url+'/api/health').close();break
  except OSError:time.sleep(.1)
 with sync_playwright() as pw:
  b=pw.chromium.launch(executable_path='/usr/bin/google-chrome',args=['--no-sandbox']);p=b.new_page(viewport={'width':1440,'height':1000});errors=[];p.on('pageerror',lambda e:errors.append(str(e)));p.goto(url);p.evaluate('localStorage.setItem("cc_cfg_tour_v1","1");localStorage.setItem("cc_tour","1")');p.goto(url+'/settings.html');p.wait_for_selector('#nerdDrop');p.wait_for_selector('.workspace-tabs');p.keyboard.press('Escape')
  def drop(data,name):
   p.locator('#menu a[href="#sec-portable"]').click();p.locator('#nerdDrop').wait_for(state='visible')
   transfer=p.evaluate_handle('([bytes,name])=>{const dt=new DataTransfer();dt.items.add(new File([new Uint8Array(bytes)],name,{type:"application/zip"}));return dt}',[data,name]);p.locator('#nerdDrop').dispatch_event('drop',{'dataTransfer':transfer})
  drop(bundle,'nerd.zip');p.get_by_role('button',name='Load and run',exact=True).wait_for();assert 'Dropped Nerd' in p.locator('#nerdReview').inner_text();assert not list((root/'nerds').glob('nerd-*')) if (root/'nerds').exists() else True;p.locator('#nerdReview').scroll_into_view_if_needed();p.locator('#nerdReview').wait_for(state='visible');p.wait_for_timeout(350);p.screenshot(path='/tmp/017-drop-review-desktop.png')
  p.get_by_role('button',name='Load and run',exact=True).click();link=p.get_by_role('link',name='Open Dropped Nerd',exact=True);link.wait_for(timeout=15000);childurl=link.get_attribute('href');child=b.new_page();child.goto(childurl);child.wait_for_selector('body');assert 'Dropped Nerd' in child.title() or 'Dropped Nerd' in child.locator('body').inner_text();answer=child.evaluate('async()=>{const r=await fetch("/api/ask",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:"How do Nerd ZIP imports work?"})});return await r.json()}');assert answer['evidence'],answer;assert 'CustomChat' in answer['answer'];child.close()
  p.locator('#menu a[href="#sec-finish"]').click();p.locator('#menu a[href="#sec-finish"]').click();p.get_by_role('tab',name='Workspace',exact=True).click();p.get_by_role('button',name='Stop',exact=True).wait_for();p.locator('#sec-finish').scroll_into_view_if_needed();p.screenshot(path='/tmp/017-workspace-running.png');folder=next((root/'nerds').glob('nerd-*'));p.get_by_role('button',name='Stop',exact=True).click();p.get_by_text('Stopped',exact=True).wait_for();assert folder.exists()
  try:urllib.request.urlopen(childurl+'/api/health',timeout=1);raise AssertionError('child still running')
  except (OSError,urllib.error.URLError):pass
  p.get_by_role('button',name='Remove…',exact=True).click();go=p.locator('.workspace-review').get_by_role('button',name='Confirm',exact=True);assert go.is_disabled();p.locator('.workspace-review').get_by_role('button',name='Cancel',exact=True).click();assert folder.exists();p.get_by_role('button',name='Remove…',exact=True).click();p.locator('.workspace-consent input').check();p.locator('.workspace-review').get_by_role('button',name='Confirm',exact=True).click();p.get_by_text('No imported workspaces yet.',exact=False).wait_for();assert not folder.exists();assert (root/'docs'/'keep.md').read_text()=='current app must stay';assert urllib.request.urlopen(url+'/api/health').status==200
  drop(make_zip({'../unsafe.txt':'x','app.yaml':'{}'}),'bad.zip');p.get_by_text('Unsafe path in bundle',exact=True).wait_for();assert not list((root/'nerds').glob('nerd-*'))
  codezip=make_zip({'app.yaml':'app: {title: Python Nerd}\nsources: [{id: plugin, type: python, entry: plugin:search}]','plugin.py':'def search(q,k):return [{"title":"Python evidence","text":"CustomChat bounded plugins run in a separate process, not a sandbox."}]'})
  drop(codezip,'python.zip');p.get_by_role('button',name='Load and run',exact=True).wait_for();assert p.get_by_role('button',name='Load and run',exact=True).is_disabled();p.locator('#nerdReview input[type=checkbox]').check();p.get_by_role('button',name='Load and run',exact=True).click();l=p.get_by_role('link',name='Open Python Nerd',exact=True);l.wait_for(timeout=15000);u=l.get_attribute('href');reply=json.loads(urllib.request.urlopen(urllib.request.Request(u+'/api/ask',data=json.dumps({'question':'How do bounded plugins work?'}).encode(),headers={'Content-Type':'application/json'})).read());assert reply['evidence'][0]['source']=='plugin';p.locator('#menu a[href="#sec-finish"]').click();p.get_by_role('tab',name='Workspace',exact=True).click();p.get_by_role('button',name='Stop',exact=True).click();p.get_by_text('Stopped',exact=True).wait_for();p.get_by_role('button',name='Remove…',exact=True).click();p.locator('.workspace-consent input').check();p.locator('.workspace-review').get_by_role('button',name='Confirm',exact=True).click();p.get_by_text('No imported workspaces yet.',exact=False).wait_for()
  p.set_viewport_size({'width':390,'height':844});drop(bundle,'nerd.zip');p.get_by_role('button',name='Load and run',exact=True).wait_for();p.locator('#nerdReview').scroll_into_view_if_needed();p.locator('#nerdReview').wait_for(state='visible');p.wait_for_timeout(350);p.screenshot(path='/tmp/017-drop-review-mobile.png');assert p.evaluate('document.documentElement.scrollWidth<=innerWidth+1');assert not errors,errors
  print('PASS installed0.1.7 desktop/phone genuine DataTransfer ZIP drop; review before load; child start/open/cited answer; manager list/stop/remove/cancel removal; current app preserved; path traversal rejected; Python review/consent and bounded cited answer; no JS errors.');b.close()
finally:proc.terminate();proc.wait();tmp.cleanup()
