/* Typed workspace extension controls, placed with the normal sections. */
(()=>{
 const el=(t,text)=>{const n=document.createElement(t);if(text!==undefined)n.textContent=text;return n};
 async function api(body){const headers={'Content-Type':'application/json'},token=localStorage.getItem('cc_token');if(token)headers.Authorization='Bearer '+token;const r=await fetch('/api/configuration-state',body?{method:'POST',headers,body:JSON.stringify(body)}:{headers});const d=await r.json();if(!r.ok)throw Error(d.error||'Cannot read workspace');return d}
 const title=k=>String(k).replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
 async function init(){const d=await api(),config=structuredClone(d.config),fields=[];let sources;
 for(let i=0;i<100;i++){sources=document.querySelector('#sec-search');if(sources?.querySelector('.source-key-card'))break;await new Promise(r=>setTimeout(r,80))}if(!sources)return;
 function number(input,name){if(!input.value.trim()||!Number.isFinite(Number(input.value)))throw Error(name+' needs a number; it cannot be empty.');return Number(input.value)}
 function fallback(value,path,host){const box=el('fieldset');box.append(el('legend','Fallback provider'));const enabled=el('input');enabled.type='checkbox';enabled.checked=!!value;enabled.dataset.workspaceField='provider.fallback.enabled';const label=el('label','Use a fallback provider');label.append(enabled);box.append(label);const body=el('div'),block=structuredClone(value||{type:'mock',model:'',base_url:'',api_key_env:'',temperature:config.provider.temperature,timeout:config.provider.timeout}),controls={};
 for(const key of ['type','model','base_url','api_key_env','temperature','timeout']){const label=el('label',title(key)),input=el(key==='type'?'select':'input');input.setAttribute('aria-label','Fallback '+title(key));input.dataset.workspaceField='provider.fallback.'+key;if(key==='type'){for(const type of ['mock','ollama','openai','openai_compatible','claude','gemini','minimax','mimo','deepseek','groq','mistral','openrouter']){const option=el('option',type==='mock'?'Demo (offline)':title(type));option.value=type;input.append(option)}}else input.type=typeof block[key]==='number'?'number':'text';input.value=block[key]??'';label.append(input);if(!['type','temperature','timeout'].includes(key)){const empty=el('small','(not filled)'),sync=()=>{empty.hidden=!!input.value.trim()};label.append(empty);input.addEventListener('input',sync);sync()}body.append(label);controls[key]=input}
 const marker=el('small','(not filled) - no fallback provider');const sync=()=>{body.hidden=!enabled.checked;marker.hidden=enabled.checked};enabled.addEventListener('change',sync);sync();box.append(marker,body,el('small','Saved only. Restart to apply. No provider is contacted here. Key fields accept an environment variable name, never a key.'));host.append(box);fields.push({path,input:enabled,value,read:()=>{if(!enabled.checked)return null;const result={...block};for(const [key,input] of Object.entries(controls))result[key]=['temperature','timeout'].includes(key)?number(input,'provider.fallback.'+key):input.value;return result}})}
 function leaf(value,path,host){if(path.join('.')==='provider.fallback'){fallback(value,path,host);return}if(Array.isArray(value)){const box=el('fieldset');box.append(el('legend',title(path.at(-1))));value.forEach((v,i)=>leaf(v,path.concat(i),box));if(!value.length)box.append(el('small','(not filled)'));host.append(box);return}if(value&&typeof value==='object'){const box=el('fieldset');box.append(el('legend',title(path.at(-1))));Object.entries(value).forEach(([k,v])=>leaf(v,path.concat(k),box));host.append(box);return}const label=el('label',title(path.at(-1))),input=el(typeof value==='string'?'textarea':'input');if(typeof value==='string')input.rows=value.includes('\n')?4:2;input.setAttribute('aria-label',path.map(title).join(' '));input.dataset.workspaceField=path.join('.');if(typeof value==='boolean'){input.type='checkbox';input.checked=value}else{input.type=typeof value==='number'?'number':'text';input.value=value??'';input.placeholder=''}label.append(input);if(typeof value==='string'||value===null){const marker=el('small','(not filled)'),sync=()=>{marker.hidden=!!input.value.trim()};label.append(marker);input.addEventListener('input',sync);sync()}host.append(label);fields.push({path,input,value})}
 function group(host,name){const box=el('details');box.className='workspace-fields';box.append(el('summary',name));host.append(box);return box}
 const sourceBox=group(sources,'Configured sources and custom API fields');config.sources.forEach((src,i)=>{const box=el('fieldset');box.append(el('legend',src.label||src.id));Object.entries(src).forEach(([k,v])=>leaf(v,['sources',i,k],box));sourceBox.append(box)});
 const covered={app:['title','tagline','accent','accent2','footer','examples','theme'],provider:['type','model','base_url','temperature'],retrieval:['top_k','query_rewrite'],prompt:['system','revise'],budget:Object.keys(config.budget||{})};
 for(const [section,values] of Object.entries(config)){if(section==='sources'||!values||Array.isArray(values)||typeof values!=='object')continue;const extras=Object.keys(values).filter(k=>!(covered[section]||[]).includes(k));if(!extras.length)continue;const target=document.querySelector(section==='app'?'#sec-wording':section==='provider'||section==='retrieval'?'#sec-model':section==='prompt'?'#sec-prompts':section==='budget'?'#sec-budget':'#sec-finish');if(!target)continue;const box=group(target,'More '+title(section)+' settings');extras.forEach(k=>leaf(values[k],[section,k],box));}
 const status=el('p');status.setAttribute('role','status');if(d.restart_required)status.textContent='Showing saved app-file values. Restart this workspace to apply them to running questions.';const save=el('button','Save source and additional fields');save.type='button';save.className='go green';save.onclick=async()=>{try{for(const {path,input,value,read} of fields){let target=config;for(const k of path.slice(0,-1))target=target[k];target[path.at(-1)]=read?read():typeof value==='boolean'?input.checked:typeof value==='number'?number(input,path.join('.')):value===null&&input.value===''?null:input.value}if(!confirm('Save these source and additional fields? Restart this workspace to apply them. No code or network request runs now.'))return;const latest=await api();if(latest.revision!==d.revision)throw Error('Workspace changed. Reload Configuration before saving.');const next=structuredClone(latest.config);for(const {path} of fields){let src=config,dst=next;for(const key of path.slice(0,-1)){src=src[key];dst=dst[key]}dst[path.at(-1)]=src[path.at(-1)]}const result=await api({config:next,revision:d.revision});d.revision=result.revision;status.textContent=result.message}catch(e){status.textContent=e.message}};const bar=el('div');bar.className='workspace-fields-save';bar.append(save,status);document.querySelector('#sec-finish').append(bar);
 }
 init().catch(()=>{});
})();
