/* Typed workspace extension controls, placed with the normal sections. */
(()=>{
 const el=(t,text)=>{const n=document.createElement(t);if(text!==undefined)n.textContent=text;return n};
 async function api(body){const headers={'Content-Type':'application/json'},token=localStorage.getItem('cc_token');if(token)headers.Authorization='Bearer '+token;const r=await fetch('/api/configuration-state',body?{method:'POST',headers,body:JSON.stringify(body)}:{headers});const d=await r.json();if(!r.ok)throw Error(d.error||'Cannot read workspace');return d}
 const title=k=>String(k).replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
 async function init(){const d=await api(),config=structuredClone(d.config),fields=[];let sources;
 for(let i=0;i<100;i++){sources=document.querySelector('#sec-search');if(sources?.querySelector('.source-key-card'))break;await new Promise(r=>setTimeout(r,80))}if(!sources)return;
 function leaf(value,path,host){if(Array.isArray(value)){const box=el('fieldset');box.append(el('legend',title(path.at(-1))));value.forEach((v,i)=>leaf(v,path.concat(i),box));if(!value.length)box.append(el('small','(not filled)'));host.append(box);return}if(value&&typeof value==='object'){const box=el('fieldset');box.append(el('legend',title(path.at(-1))));Object.entries(value).forEach(([k,v])=>leaf(v,path.concat(k),box));host.append(box);return}const label=el('label',title(path.at(-1))),input=el(typeof value==='string'&&value.includes('\n')?'textarea':'input');input.setAttribute('aria-label',path.map(title).join(' '));input.dataset.workspaceField=path.join('.');if(typeof value==='boolean'){input.type='checkbox';input.checked=value}else{input.type=typeof value==='number'?'number':'text';input.value=value??'';input.placeholder='(not filled)'}label.append(input);if(value===''||value===null)label.append(el('small','(not filled)'));host.append(label);fields.push({path,input,value})}
 function group(host,name){const box=el('details');box.className='workspace-fields';box.append(el('summary',name));host.append(box);return box}
 const sourceBox=group(sources,'Configured sources and custom API fields');config.sources.forEach((src,i)=>{const box=el('fieldset');box.append(el('legend',src.label||src.id));Object.entries(src).forEach(([k,v])=>leaf(v,['sources',i,k],box));sourceBox.append(box)});
 const covered={app:['title','tagline','accent','accent2','footer','examples','theme'],provider:['type','model','base_url','temperature'],retrieval:['top_k','query_rewrite'],prompt:['system','revise'],budget:Object.keys(config.budget||{})};
 for(const [section,values] of Object.entries(config)){if(section==='sources'||!values||Array.isArray(values)||typeof values!=='object')continue;const extras=Object.keys(values).filter(k=>!(covered[section]||[]).includes(k));if(!extras.length)continue;const target=document.querySelector(section==='app'?'#sec-wording':section==='provider'||section==='retrieval'?'#sec-model':section==='prompt'?'#sec-prompts':section==='budget'?'#sec-budget':'#sec-finish');if(!target)continue;const box=group(target,'More '+title(section)+' settings');extras.forEach(k=>leaf(values[k],[section,k],box));}
 const status=el('p');status.setAttribute('role','status');const save=el('button','Save source and additional fields');save.type='button';save.className='go green';save.onclick=async()=>{try{for(const {path,input,value} of fields){let target=config;for(const k of path.slice(0,-1))target=target[k];target[path.at(-1)]=typeof value==='boolean'?input.checked:typeof value==='number'?Number(input.value):value===null&&input.value===''?null:input.value}if(!confirm('Save these source and additional fields? Restart this workspace to apply them. No code or network request runs now.'))return;const latest=await api();if(latest.revision!==d.revision)throw Error('Workspace changed. Reload Configuration before saving.');const next=structuredClone(latest.config);for(const {path} of fields){let src=config,dst=next;for(const key of path.slice(0,-1)){src=src[key];dst=dst[key]}dst[path.at(-1)]=src[path.at(-1)]}const result=await api({config:next,revision:d.revision});d.revision=result.revision;status.textContent=result.message}catch(e){status.textContent=e.message}};const bar=el('div');bar.className='workspace-fields-save';bar.append(save,status);document.querySelector('#sec-finish').append(bar);
 }
 init().catch(()=>{});
})();
