/* All app-file fields, loaded from the owner workspace. No secret values. */
(()=>{
 const $=s=>document.querySelector(s),el=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n};
 async function api(body){const headers={'Content-Type':'application/json'},token=localStorage.getItem('cc_token');if(token)headers.Authorization='Bearer '+token;const r=await fetch('/api/configuration-state',body?{method:'POST',headers,body:JSON.stringify(body)}:{headers}),d=await r.json();if(!r.ok)throw Error(d.error||'Cannot read workspace');return d}
 async function init(){const d=await api(),host=el('details');host.id='allConfigFields';host.className='all-config-fields';host.append(el('summary','All app fields · current workspace'),el('p','These are this Nerd’s actual app-file values. Save writes its app file; restart this workspace to apply them. Secret values stay private. Existing saved keys remain available to the model.'));
 const fields=[];
 function walk(value,path){if(value&&typeof value==='object'&&!Array.isArray(value)){for(const [k,v] of Object.entries(value))walk(v,path.concat(k));return}const label=el('label',path.join('.'));const input=el('textarea');input.rows=Array.isArray(value)?Math.min(8,Math.max(2,value.length+1)):2;input.value=JSON.stringify(value,null,2);input.setAttribute('aria-label',path.join('.'));label.append(input);host.append(label);fields.push({path,input});}
 walk(d.config,[]);const status=el('p');status.setAttribute('role','status');const save=el('button','Save app fields');save.type='button';save.className='go green';save.onclick=async()=>{try{const config=structuredClone(d.config);for(const {path,input} of fields){let target=config;for(const key of path.slice(0,-1))target=target[key];target[path.at(-1)]=JSON.parse(input.value);}if(!confirm('Save these app-file fields? Restart is required. This may change model, sources, access, storage and network settings after restart. No new connector code runs now.'))return;const r=await api({config,revision:d.revision});d.revision=r.revision;status.textContent=r.message;}catch(e){status.textContent=e.message}};host.append(save,status);($('#loadedApp')||$('#lead')).after(host);}
 init().catch(()=>{});
})();
