(() => {
 const drop=document.getElementById('nerdDrop'),input=document.getElementById('nerdFile'),out=document.getElementById('nerdReview');if(!drop)return;
 const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n};
 async function api(path,body){const h={'Content-Type':'application/json'},t=localStorage.getItem('cc_token');if(t)h.Authorization='Bearer '+t;const r=await fetch(path,{method:'POST',headers:h,body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load');return d}
 function row(label,value){const n=el('div',undefined,'import-row');n.append(el('b',label),el('span',value));return n}
 function staticPreview(d){const data=d.preview||{},n=el('aside',undefined,'import-preview');n.setAttribute('aria-label','Static imported Nerd preview');const colors=data.colors||{};for(const key of ['bg','ink','brand','surface','muted','line','bot'])if(/^#[0-9a-f]{6}$/i.test(colors[key]||''))n.style.setProperty('--bundle-'+key,colors[key]);n.append(el('span','BUNDLE PREVIEW · STATIC','import-badge'),el('h2',data.title||d.title),el('p',data.tagline||d.tagline));const greeting=el('div',undefined,'import-greeting');greeting.append(el('b','Welcome'),el('p',(data.examples||[])[0]||'Ask a question after loading this Nerd.'));n.append(greeting,row('Answers',d.provider==='mock'?'Offline Demo, not a live model':d.provider+' · '+d.model),row('Evidence',d.sources.map(s=>s.label).join(', ')||'No sources configured'),el('p','Reviewed bundle wording and colors only. Scripts, connectors, images, fonts and external assets do not run here. No answer is generated.','h'));const disabled=el('div','Question input is disabled. Load only after reviewing the files and code.','import-disabled');n.append(disabled);return n}
 let seq=0;
 async function review(file){if(!file)return;const now=++seq;if(file.size>8*1024*1024){out.textContent='Choose a bundle under 8 MB';return}drop.classList.add('reading');out.textContent='Reading bundle. Nothing is running yet.';try{const bytes=new Uint8Array(await file.arrayBuffer());let raw='';for(let i=0;i<bytes.length;i+=8192)raw+=String.fromCharCode(...bytes.subarray(i,i+8192));const d=await api('/api/nerds/review',{name:file.name,data:btoa(raw)});if(now!==seq)return;
 const grid=el('div',undefined,'import-grid'),card=el('section',undefined,'import-card'),filetag=el('div',undefined,'import-file');filetag.append(el('span','BUNDLE REVIEWED','import-badge'),el('b',file.name),el('small','Current app stays unchanged'));card.append(filetag,el('h2',d.title),el('p',d.tagline),row('Answers',d.provider==='mock'?'Offline Demo':d.provider+' · '+d.model),row('Sources',d.sources.map(s=>s.label+' ('+s.type+')').join(', ')||'No sources configured'),row('Keys',(d.required_env||[]).join(', ')||'None declared'));
 const notices=el('div',undefined,'import-notices');notices.append(el('b','Before you load'),el('p','Separate local workspace. Keys, accounts and chat history stay out. Write actions are off for imported apps.'));if(d.code.length)notices.append(el('p','Python uses bounded mode, NOT a sandbox. Host files/network remain accessible. Review all code before allowing it.'));d.readiness.rows.filter(r=>['setup','warning','blocked'].includes(r.kind)).forEach(r=>notices.append(el('p',r.item+': '+r.message)));card.append(notices);
 const scan=d.auto_review;if(scan){const report=el('section',undefined,'import-scan');report.append(el('span','LOCAL STATIC REVIEW · NOT A SAFETY VERDICT','import-badge'),el('h3','What this app declares'),el('p',scan.purpose),el('small',scan.purpose_basis),row('Files',scan.file_count+' total · '+scan.python_files+' Python · '+scan.functions+' functions'),row('Imports',scan.imports.join(', ')||'No import statements detected'));const names={network:'Network-like calls',environment:'Environment access',files:'File-like calls',process:'Process-like calls',dynamic:'Dynamic code',unparsed:'Unparsed Python'};Object.entries(names).forEach(([k,label])=>report.append(row(label,scan.counts[k]?scan.counts[k]+' detected patterns':'No recognized patterns detected')));const limits=el('div',undefined,'import-notices');limits.append(el('b','Read the complete code before loading'),el('p',scan.limits));report.append(limits);const details=el('details',undefined,'import-details');details.append(el('summary','Scan evidence and scope'),el('p',scan.scope));scan.findings.forEach(f=>details.append(el('p',names[f.category]+': '+f.pattern+' · '+f.path+':'+f.line)));if(scan.truncated)details.append(el('p','Evidence list capped at80 findings; counts include all detected patterns.'));report.append(details);card.append(report)}
 const defaults=el('details',undefined,'import-details');defaults.append(el('summary','Files, defaults and source inventory'));(d.preview?.files||[]).forEach(f=>defaults.append(el('small',f)));d.readiness.rows.filter(r=>!['setup','warning','blocked'].includes(r.kind)).forEach(r=>defaults.append(el('p',r.item+': '+r.message)));card.append(defaults);
 let allow=null;if(d.code.length){d.code.forEach(c=>{const details=el('details',undefined,'import-code');details.append(el('summary','Review '+c.path),el('pre',c.text));card.append(details)});const label=el('label',undefined,'import-consent');allow=el('input');allow.type='checkbox';label.append(allow,document.createTextNode(' I reviewed this code and allow it to run locally.'));card.append(label)}
 const status=el('p','Separate workspace. Current Nerd stays open.','import-status');status.setAttribute('role','status');status.setAttribute('aria-live','polite');const btn=el('button','Load and run','go green import-load');btn.type='button';btn.disabled=!!allow;if(allow)allow.onchange=()=>btn.disabled=!allow.checked;
 btn.onclick=async()=>{btn.disabled=true;btn.textContent='Starting separate Nerd…';card.classList.add('starting');status.textContent='Starting a separate local Nerd...';try{const loaded=await api('/api/nerds/load',{token:d.token,allow_code:!!allow?.checked});const a=el('a','Open '+loaded.title,'go green');a.href=loaded.url;a.target='_blank';a.rel='noopener';status.replaceChildren(a,el('small','Separate workspace is running.'));btn.textContent='Loaded';btn.hidden=true;card.classList.add('loaded');}catch(e){status.textContent=e.message;btn.textContent='Try load again';btn.disabled=allow?!allow.checked:false}finally{card.classList.remove('starting')}};card.append(btn,status,el('small',d.readiness.scope));grid.append(card,staticPreview(d));out.replaceChildren(grid);out.classList.add('has-review');
 }catch(e){if(now===seq)out.textContent=e.message}finally{drop.classList.remove('reading')}}
 input.addEventListener('change',()=>review(input.files[0]));drop.addEventListener('dragover',e=>{e.preventDefault();drop.classList.add('over')});drop.addEventListener('dragleave',()=>drop.classList.remove('over'));drop.addEventListener('drop',e=>{e.preventDefault();drop.classList.remove('over');review(e.dataTransfer.files[0])});drop.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();input.click()}});
})();
