/* Private management; live requests happen only after a review and explicit click. */
(() => {
 const root=document.getElementById('workspacePanel');if(!root)return;
 const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n};
 async function api(path,body){const h={'Content-Type':'application/json'},token=localStorage.getItem('cc_token');if(token)h.Authorization='Bearer '+token;const r=await fetch(path,body===undefined?{headers:h}:{method:'POST',headers:h,body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed');return d}
 const button=(text,fn)=>{const b=el('button',text,'go ghost');b.type='button';b.onclick=async()=>{b.disabled=true;try{await fn()}catch(e){status.textContent=e.message}finally{b.disabled=false}};return b};
 const nav=el('div',undefined,'workspace-tabs');nav.setAttribute('role','tablist');nav.setAttribute('aria-label','Workspace tools');const body=el('div',undefined,'workspace-body'),status=el('p','','h');status.setAttribute('role','status');root.append(nav,body,status);
 function showReview(plan,onConfirm){const box=el('div',undefined,'workspace-review');box.setAttribute('role','region');box.setAttribute('aria-label','Review action');box.append(el('h3','Review before continuing'));if(plan.notice)box.append(el('p',plan.notice));if(plan.diff)plan.diff.forEach(d=>box.append(el('p',d.field+': '+JSON.stringify(d.current)+' → '+JSON.stringify(d.restore))));if(plan.questions)box.append(el('p','Questions: '+plan.questions.join(' / ')),el('p','Model calls: '+plan.model_calls+'; sources: '+(plan.sources.join(', ')||'none')));if(plan.chats!==undefined)box.append(el('p',plan.chats+' chats / '+plan.turns+' turns'));
 const consent=el('input');consent.type='checkbox';const label=el('label');label.className='workspace-consent';label.append(consent,document.createTextNode(' I reviewed this action and want to continue.'));const go=button('Confirm',async()=>{if(!consent.checked)return;await onConfirm(plan);box.remove()});go.disabled=true;consent.onchange=()=>go.disabled=!consent.checked;box.append(label,go,button('Cancel',()=>box.remove()));body.append(box);box.scrollIntoView({block:'nearest'});}
 async function poll(id){status.textContent='Test running. This page checks the local job, not the external service again.';for(let i=0;i<900;i++){await new Promise(r=>setTimeout(r,1000));const r=await api('/api/workspace/job?id='+encodeURIComponent(id));if(r.state==='running')continue;status.textContent=r.notice||r.message||r.state;const box=el('section',undefined,'workspace-results');box.append(el('h3','Test results'));
 for(const row of r.results||[]){if(row.question){const d=el('details');d.append(el('summary',row.question+(row.previous_answer===undefined||row.previous_answer===null?' · first run':row.changed?' · changed':' · unchanged')),el('p','Comparison only. No correctness verdict.'));const columns=el('div',undefined,'workspace-compare');for(const [label,answer,cites] of [['Current',row.answer,row.citations],['Previous',row.previous_answer,row.previous_citations]]){const col=el('div');col.append(el('h4',label),el('pre',answer??'No previous run'),el('p','Citations: '+(cites||[]).map(c=>c.title||c.id).join(', ')));columns.append(col)}d.append(columns);if(row.message)d.append(el('p',row.message));if(row.source_errors?.length)d.append(el('p','Source diagnostics: '+row.source_errors.map(x=>x.category+': '+x.message).join('; ')));box.append(d)}else box.append(el('p',row.item+': '+(row.ok?'Request completed':'Needs attention')+' · '+row.message));}body.append(box);return;}}
 async function live(kind){const select=el('div');select.append(el('p','Choose the services to contact. No request runs until you review it.'));const model=el('input');model.type='checkbox';model.checked=true;const ml=el('label');ml.append(model,document.createTextNode(kind==='smoke'?' Run configured model for saved questions':' Check configured model'));if(kind==='smoke')model.disabled=true;select.append(ml);const sources=(await api('/api/workspace/sources')).sources,checks=[];for(const s of sources){const c=el('input');c.type='checkbox';c.value=s.id;const label=el('label');label.append(c,document.createTextNode(' '+s.label));select.append(label);checks.push(c)}
 select.append(button('Review '+(kind==='smoke'?'test run':'live checks'),async()=>{const plan=await api('/api/workspace/'+kind+'/review',{model:model.checked,sources:checks.filter(c=>c.checked).map(c=>c.value)});showReview(plan,async()=>{const r=await api('/api/workspace/'+kind+'/run',{ticket:plan.ticket,confirmed:true});poll(r.id).catch(e=>status.textContent=e.message)})}));body.append(select);}
 async function setup(){const d=await api('/api/workspace/status');body.append(el('p','Local checks only. Live services have not been tested.','h'));const summaries={'Model':r=>r.state==='demo'?'Offline Demo':r.state,'Credential':r=>r.state==='present / not required'?(d.rows.some(x=>x.item==='Model'&&x.state==='demo')?'No key needed':'Key available; not tested'):r.state==='setup'?'Add a key':r.state,'Evidence sources':r=>r.state==='configured'?'Sources added':'Add a source','Data audience':r=>'Review before sharing','Connector code':r=>r.state==='ready'?'No Python connector':r.state};for(const row of d.rows){const r=el('div',undefined,'workspace-row workspace-status-row');let short=summaries[row.item]?.(row);if(!short)short=row.state==='indexed'?'Local documents indexed':row.state;r.append(el('b',row.item),el('span',short));body.append(r)}const details=el('details',undefined,'workspace-check-details');details.append(el('summary','Check details and limits'));for(const row of d.rows)details.append(el('p',row.item+': '+row.state+' · '+row.detail));body.append(details);if(d.last_live){const old=el('details',undefined,'workspace-check-details');old.append(el('summary','Last live check · '+new Date(d.last_live.at*1000).toLocaleString()));d.last_live.results.forEach(r=>old.append(el('p',r.item+': '+r.message)));old.append(el('p','A past result does not prove current availability.'));body.append(old)}body.append(button('Choose live checks',()=>live('preflight')),el('p','Nothing is contacted until you review and confirm.','h'));}
 async function workspace(){body.append(el('p','Current app stays open. Imported Nerds run separately. Stopped workspaces are kept on disk; reimport the original bundle to start a new reviewed copy.'));const d=await api('/api/nerds');if(!d.workspaces.length)body.append(el('p','No imported workspaces yet. Load a Nerd from Portable app.'));for(const w of d.workspaces){const row=el('div',undefined,'workspace-row');row.append(el('b',w.title),el('span',w.running?'Running':'Stopped'));const controls=el('div',undefined,'workspace-actions');if(w.running){const a=el('a','Open','go ghost');a.href=w.url;a.target='_blank';a.rel='noopener';controls.append(a,button('Stop',async()=>{await api('/api/nerds/stop',{id:w.id});await open('Workspace')}))}controls.append(button('Remove…',async()=>{showReview({notice:'Remove '+w.title+' ('+w.id+') and all its local imported files and chats? This cannot be undone. Current app and other workspaces are untouched.'},async()=>{await api('/api/nerds/remove',{id:w.id,confirmed:true});await open('Workspace')})}));row.append(controls);body.append(row)}body.append(el('p','Python bounded mode is NOT a sandbox. Imported code can still access host files and the network. Review it first.','h'));}
 async function history(){const d=await api('/api/workspace/history');body.append(el('p',d.scope));if(!d.revisions.length)body.append(el('p','No previous model/retrieval settings yet. Applying a change saves the previous settings here.'));for(const name of d.revisions){const row=el('div',undefined,'workspace-row');row.append(el('b',new Date(Number(name.replace('history-',''))/1e6).toLocaleString()),button('Compare / restore',async()=>{const r=await api('/api/workspace/history/review',{name});showReview(r,async()=>{await api('/api/workspace/history/restore',{ticket:r.ticket,confirmed:true});status.textContent='Restored. Reload Configuration to refresh its fields.'})}));body.append(row)}}
 async function backup(){body.append(el('p','Private conversation content, separate from shareable Nerd export. This archive excludes account credentials, uploads, profile, feedback and API keys. Your own chat text may contain sensitive data. Keep it private.'));body.append(button('Download private chat archive',async()=>{const data=await api('/api/workspace/archive'),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=el('a');a.href=url;a.download='customchat-private-chats.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}));const input=el('input');input.type='file';input.accept='.json,application/json';input.setAttribute('aria-label','Private chat archive to restore');input.onchange=async()=>{try{const file=input.files[0];if(!file)return;if(file.size>8*1024*1024)throw Error('Choose an archive under 8 MB');const r=await api('/api/workspace/archive/review',{archive:JSON.parse(await file.text())});showReview(r,async()=>{const result=await api('/api/workspace/archive/restore',{ticket:r.ticket,confirmed:true});status.textContent='Added '+result.imported+' chats to your account.'})}catch(e){status.textContent=e.message}};body.append(el('h3','Restore to this account'),input);}
 async function questions(){body.append(el('p','Save up to 10 questions, one per line. Run after review. Compare answers and citations without treating a match as proof of correctness. Tests do not create chats.'));const area=el('textarea');area.rows=6;area.setAttribute('aria-label','Saved smoke-test questions');area.value=(await api('/api/workspace/questions')).questions.join('\n');body.append(area,button('Save questions',async()=>{await api('/api/workspace/questions',{questions:area.value.split('\n').map(s=>s.trim()).filter(Boolean)});status.textContent='Saved privately to your account.'}),button('Choose test services',()=>live('smoke')));}
 async function deploy(){body.append(el('p','Plan only. No cloud account access, credentials, resources or spending. Your entered account and prices are not verified.'));const fields={};for(const [key,label] of [['target','Target / service'],['account','Account label (not a credential)'],['region','Region'],['audience','Audience'],['cost_limit','Monthly cost limit / constraints'],['rollback','Rollback and backup plan']]){const wrap=el('label',label);let input;if(key==='audience'){input=el('select');['private','team','public'].forEach(v=>{const o=el('option',v);o.value=v;input.append(o)})}else{input=el(key==='rollback'?'textarea':'input');input.maxLength=600}input.setAttribute('aria-label',label);fields[key]=input;wrap.append(input);body.append(wrap)}body.append(button('Prepare deployment plan',async()=>{const plan=Object.fromEntries(Object.entries(fields).map(([k,v])=>[k,v.value]));const r=await api('/api/workspace/deploy',{plan});const box=el('div',undefined,'workspace-review');box.append(el('h3','Deployment review'),el('p',r.notice));r.checks.forEach(c=>box.append(el('p',c.item+' · '+c.state+': '+c.detail)));r.next_steps.forEach(c=>box.append(el('p',c)));box.append(button('Download plan',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(r,null,2)],{type:'application/json'})),a=el('a');a.href=url;a.download='customchat-deploy-plan.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}));body.append(box)}));}
 const panels={Setup:setup,Workspace:workspace,Changes:history,Backup:backup,'Test questions':questions,Deploy:deploy};let seq=0;
 async function open(name){[...nav.children].forEach(b=>b.disabled=true);seq++;const now=seq;body.replaceChildren();status.textContent='';[...nav.children].forEach(b=>b.setAttribute('aria-selected',String(b.textContent===name)));try{await panels[name]()}catch(e){if(now===seq)status.textContent=e.message}finally{[...nav.children].forEach(b=>b.disabled=false)}}
 for(const name of Object.keys(panels)){const b=button(name,()=>open(name));b.setAttribute('role','tab');b.setAttribute('aria-selected','false');nav.append(b)}
 api('/api/settings').then(d=>{if(!d.can_edit){root.textContent='Workspace management is available to the app owner.';return}open('Setup')}).catch(e=>status.textContent=e.message);
})();
